name: report
channels:
  - pytorch
  - conda-forge
dependencies:
  - geopandas = 0.13.0
  - geodatasets =  2023.3.0
  - folium = 0.14.0
  - jupyter = 1.0.0
  - matplotlib = 3.7.5
  - scienceplots = 2.1.0
  - movingpandas = 0.16.0
  - numpy = 1.25.0
  - pandas = 2.0.3
  - python
  - pytorch = 1.0.2
  - scipy = 1.11.1
  - seaborn = 0.12.2
  - scikit-learn = 1.3.0

  # Latex https://miktex.org/download